version: "3"

services:
  tanuki:
    image: ghcr.io/fiwippi/tanuki:latest
    command: -config /data/config.json run
    ports:
      - "8001:8001"
    volumes:
      - ./library/:/library
      - ./data:/data
