---
services:
  tanuki:
    image: ghcr.io/fiwippi/tanuki:latest
    command: -config /config.toml
    ports:
      - "8001:8001"
    volumes:
      - ./config.toml:/config.toml
      - ./library/:/library
      - ./data:/data
