version: "3"

services:
  tanuki:
    container_name: tanuki
    build: .
    restart: unless-stopped
    volumes:
      - ./library/:/library
      - ./data:/data
      - ./config:/config
    ports:
      - "8096:8096"